-- SmartLog V2 :: PostgreSQL schema
-- generated by scripts/migrate_sqlite_to_pg.py
-- FKs are added after table creation so mutual cycles resolve.


CREATE TABLE anomaly_log (
	id SERIAL NOT NULL, 
	employee_id INTEGER, 
	anomaly_type VARCHAR(100) NOT NULL, 
	severity VARCHAR(20), 
	score FLOAT, 
	description TEXT, 
	detected_date DATE NOT NULL, 
	metadata_json TEXT, 
	resolved BOOLEAN, 
	resolved_at TIMESTAMP WITHOUT TIME ZONE, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE backup_config (
	id SERIAL NOT NULL, 
	encryption_enabled BOOLEAN, 
	encryption_algorithm VARCHAR(20), 
	master_key_hash VARCHAR(128), 
	salt_hex VARCHAR(128), 
	compression_enabled BOOLEAN, 
	compression_level INTEGER, 
	auto_verify BOOLEAN, 
	verify_interval_days INTEGER, 
	retention_days INTEGER, 
	max_local_backups INTEGER, 
	max_server_backups INTEGER, 
	secure_delete_passes INTEGER, 
	notification_email VARCHAR(200), 
	backup_directory VARCHAR(500), 
	server_backup_directory VARCHAR(500), 
	auto_cleanup_enabled BOOLEAN, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE backup_metadata (
	id SERIAL NOT NULL, 
	filename VARCHAR(255) NOT NULL, 
	backup_type VARCHAR(20), 
	size_bytes BIGINT, 
	checksum VARCHAR(128), 
	encrypted BOOLEAN, 
	location VARCHAR(50), 
	filepath VARCHAR(500), 
	status VARCHAR(20), 
	verified_at TIMESTAMP WITHOUT TIME ZONE, 
	verified_by INTEGER, 
	locked BOOLEAN, 
	locked_until TIMESTAMP WITHOUT TIME ZONE, 
	description TEXT, 
	manifest_json TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	deleted_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE backup_schedules (
	id SERIAL NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	backup_type VARCHAR(20), 
	frequency VARCHAR(20), 
	frequency_value INTEGER, 
	time_str VARCHAR(10), 
	destination VARCHAR(50), 
	encrypt BOOLEAN, 
	is_active BOOLEAN, 
	last_run TIMESTAMP WITHOUT TIME ZONE, 
	last_status VARCHAR(20), 
	last_duration FLOAT, 
	last_size BIGINT, 
	next_run TIMESTAMP WITHOUT TIME ZONE, 
	total_runs INTEGER, 
	successful_runs INTEGER, 
	failed_runs INTEGER, 
	notify_on_success BOOLEAN, 
	notify_on_failure BOOLEAN, 
	retention_count INTEGER, 
	employee_filter TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE blocked_ips (
	id SERIAL NOT NULL, 
	ip_address VARCHAR(50) NOT NULL, 
	violation_count INTEGER, 
	banned_at TIMESTAMP WITHOUT TIME ZONE, 
	ban_expiry TIMESTAMP WITHOUT TIME ZONE, 
	is_permanent BOOLEAN, 
	is_active BOOLEAN, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (ip_address)
)

;


CREATE TABLE branches (
	id SERIAL NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	address VARCHAR(200), 
	phone VARCHAR(20), 
	is_active BOOLEAN, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE branding_config (
	id SERIAL NOT NULL, 
	tenant_name VARCHAR(100), 
	logo_url VARCHAR(300), 
	primary_color VARCHAR(10), 
	accent_color VARCHAR(10), 
	bg_color VARCHAR(10), 
	card_color VARCHAR(10), 
	custom_css TEXT, 
	company_lat FLOAT, 
	company_lng FLOAT, 
	allowed_radius_meters INTEGER, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE companies (
	id SERIAL NOT NULL, 
	name_ar VARCHAR(200) NOT NULL, 
	name_en VARCHAR(200), 
	domain VARCHAR(100), 
	email VARCHAR(120), 
	phone VARCHAR(20), 
	address TEXT, 
	logo_url VARCHAR(300), 
	primary_color VARCHAR(7), 
	bg_color VARCHAR(7), 
	plan VARCHAR(20), 
	is_active BOOLEAN, 
	is_verified BOOLEAN, 
	max_employees INTEGER, 
	max_devices INTEGER, 
	features_json TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	deleted_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (domain)
)

;


CREATE TABLE departments (
	id SERIAL NOT NULL, 
	code VARCHAR(20) NOT NULL, 
	name_ar VARCHAR(50) NOT NULL, 
	name_en VARCHAR(50), 
	icon VARCHAR(50), 
	color VARCHAR(7), 
	description_ar VARCHAR(200), 
	description_en VARCHAR(200), 
	dept_type VARCHAR(20), 
	is_active BOOLEAN, 
	inactive_reason VARCHAR(200), 
	parent_id INTEGER, 
	dept_level INTEGER, 
	manager_id INTEGER, 
	deputy_id INTEGER, 
	cost_center_code VARCHAR(20), 
	min_staff_required INTEGER, 
	max_staff_capacity INTEGER, 
	allowed_employment_types VARCHAR(200), 
	default_shift_id INTEGER, 
	grace_period_override INTEGER, 
	remote_work_allowed BOOLEAN, 
	break_duration_policy INTEGER, 
	overtime_max_weekly INTEGER, 
	overtime_requires_approval BOOLEAN, 
	overtime_auto_approve_under INTEGER, 
	whatsapp_group_id VARCHAR(50), 
	alert_settings TEXT, 
	alert_threshold_minutes INTEGER, 
	alert_understaffing_threshold INTEGER, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (code)
)

;


CREATE TABLE document_references (
	id SERIAL NOT NULL, 
	reference_code VARCHAR(30) NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE email_logs (
	id SERIAL NOT NULL, 
	to_email VARCHAR(120) NOT NULL, 
	subject VARCHAR(200) NOT NULL, 
	body TEXT NOT NULL, 
	status VARCHAR(20), 
	sent_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE email_templates (
	id SERIAL NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	subject VARCHAR(200) NOT NULL, 
	body TEXT NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE employee_grades (
	id SERIAL NOT NULL, 
	code VARCHAR(20) NOT NULL, 
	name_ar VARCHAR(100) NOT NULL, 
	category VARCHAR(30) NOT NULL, 
	level INTEGER NOT NULL, 
	base_salary FLOAT, 
	responsibility_allowance FLOAT, 
	hazard_allowance FLOAT, 
	transport_allowance FLOAT, 
	housing_allowance FLOAT, 
	medical_insurance_level VARCHAR(30), 
	annual_leave_days INTEGER, 
	sick_leave_days INTEGER, 
	retirement_age INTEGER, 
	pension_rate FLOAT, 
	min_years_for_promotion INTEGER, 
	required_qualification VARCHAR(50), 
	next_grade_id INTEGER, 
	is_active BOOLEAN, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (code)
)

;


CREATE TABLE employees (
	id SERIAL NOT NULL, 
	username VARCHAR(20) NOT NULL, 
	full_name VARCHAR(100) NOT NULL, 
	department VARCHAR(50) NOT NULL, 
	password_hash VARCHAR(256) NOT NULL, 
	base_salary_encrypted TEXT, 
	overtime_multiplier FLOAT, 
	device_id VARCHAR(120), 
	role VARCHAR(10), 
	is_active BOOLEAN, 
	email VARCHAR(120), 
	email_encrypted TEXT, 
	phone VARCHAR(20), 
	phone_encrypted TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	department_id INTEGER, 
	phone_country_code VARCHAR(5), 
	national_id VARCHAR(20), 
	date_of_birth DATE, 
	gender VARCHAR(10), 
	marital_status VARCHAR(20), 
	address TEXT, 
	profile_photo VARCHAR(200), 
	job_title VARCHAR(100), 
	employment_type VARCHAR(20), 
	hire_date DATE, 
	contract_end_date DATE, 
	no_end_date BOOLEAN, 
	manager_id INTEGER, 
	shift_type_id INTEGER, 
	branch_id INTEGER, 
	biotime_emp_id INTEGER, 
	assigned_devices TEXT, 
	last_sync TIMESTAMP WITHOUT TIME ZONE, 
	fp_enrolled BOOLEAN, 
	face_enrolled BOOLEAN, 
	sync_status VARCHAR(20), 
	housing_allowance FLOAT, 
	transport_allowance FLOAT, 
	other_allowances TEXT, 
	payment_method VARCHAR(20), 
	bank_account_number VARCHAR(30), 
	bank_name VARCHAR(60), 
	permission_level VARCHAR(30), 
	force_password_change BOOLEAN, 
	two_factor_enabled BOOLEAN, 
	otp_secret VARCHAR(32), 
	password_changed_at TIMESTAMP WITHOUT TIME ZONE, 
	emergency_contact_name VARCHAR(100), 
	emergency_relationship VARCHAR(30), 
	emergency_phone VARCHAR(20), 
	emergency_phone2 VARCHAR(20), 
	company_id INTEGER, 
	deleted_at TIMESTAMP WITHOUT TIME ZONE, 
	deleted_by INTEGER, 
	delete_reason VARCHAR(300), 
	PRIMARY KEY (id), 
	UNIQUE (national_id)
)

;


CREATE TABLE geofence_zones (
	id SERIAL NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	name_en VARCHAR(100), 
	zone_type VARCHAR(20), 
	coordinates TEXT, 
	center_lat FLOAT, 
	center_lng FLOAT, 
	radius FLOAT, 
	color VARCHAR(10), 
	address VARCHAR(300), 
	purpose VARCHAR(300), 
	work_hours_start VARCHAR(5), 
	work_hours_end VARCHAR(5), 
	work_days TEXT, 
	is_active BOOLEAN, 
	is_restricted BOOLEAN, 
	is_trusted BOOLEAN, 
	alert_on_entry BOOLEAN, 
	alert_on_exit BOOLEAN, 
	assigned_employees TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE holiday_calendar (
	id SERIAL NOT NULL, 
	name VARCHAR(200) NOT NULL, 
	date DATE NOT NULL, 
	type VARCHAR(50), 
	is_recurring BOOLEAN, 
	description TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_holiday_name_date UNIQUE (name, date)
)

;


CREATE TABLE leave_types (
	id SERIAL NOT NULL, 
	code VARCHAR(30) NOT NULL, 
	name_ar VARCHAR(100) NOT NULL, 
	default_days INTEGER, 
	is_paid BOOLEAN, 
	is_recurring BOOLEAN, 
	max_consecutive INTEGER, 
	requires_approval BOOLEAN, 
	notes TEXT, 
	is_active BOOLEAN, 
	PRIMARY KEY (id), 
	UNIQUE (code)
)

;


CREATE TABLE login_attempts (
	id SERIAL NOT NULL, 
	ip_address VARCHAR(50) NOT NULL, 
	attempts INTEGER, 
	last_attempt TIMESTAMP WITHOUT TIME ZONE, 
	blocked_until TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (ip_address)
)

;


CREATE TABLE model_performance_log (
	id SERIAL NOT NULL, 
	model_key VARCHAR(100) NOT NULL, 
	prediction_date DATE NOT NULL, 
	total_predictions INTEGER, 
	correct_predictions INTEGER, 
	accuracy FLOAT, 
	precision FLOAT, 
	recall FLOAT, 
	f1_score FLOAT, 
	training_duration_seconds FLOAT, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE model_registry (
	id SERIAL NOT NULL, 
	model_key VARCHAR(100) NOT NULL, 
	model_type VARCHAR(100) NOT NULL, 
	file_path VARCHAR(500), 
	training_date TIMESTAMP WITHOUT TIME ZONE, 
	metrics_json TEXT, 
	is_active BOOLEAN, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE permissions (
	id SERIAL NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	code VARCHAR(50) NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (code)
)

;


CREATE TABLE prediction_result (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	prediction_type VARCHAR(50) NOT NULL, 
	prediction_date DATE NOT NULL, 
	probability FLOAT, 
	risk_level VARCHAR(20), 
	was_correct BOOLEAN, 
	actual_outcome VARCHAR(50), 
	metadata_json TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE rbac_permissions (
	id SERIAL NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	name_ar VARCHAR(100), 
	code VARCHAR(100) NOT NULL, 
	description TEXT, 
	module VARCHAR(50), 
	is_high_risk BOOLEAN, 
	requires_2fa BOOLEAN, 
	requires_approval BOOLEAN, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (code)
)

;


CREATE TABLE rbac_role_templates (
	id SERIAL NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	description TEXT, 
	permissions TEXT, 
	scope VARCHAR(20), 
	risk_level VARCHAR(20), 
	is_builtin BOOLEAN, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE risk_assessment (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	assessment_type VARCHAR(50) NOT NULL, 
	risk_score FLOAT, 
	risk_level VARCHAR(20), 
	factors_json TEXT, 
	assessment_date DATE NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE roles (
	id SERIAL NOT NULL, 
	name VARCHAR(50) NOT NULL, 
	permissions TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (name)
)

;


CREATE TABLE shift_types (
	id SERIAL NOT NULL, 
	name VARCHAR(50) NOT NULL, 
	start_hour INTEGER NOT NULL, 
	start_min INTEGER, 
	end_hour INTEGER NOT NULL, 
	end_min INTEGER, 
	color VARCHAR(10), 
	description VARCHAR(200), 
	min_staff INTEGER, 
	max_staff INTEGER, 
	is_overnight BOOLEAN, 
	is_active BOOLEAN, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE sms_logs (
	id SERIAL NOT NULL, 
	to_phone VARCHAR(20) NOT NULL, 
	message VARCHAR(160) NOT NULL, 
	status VARCHAR(20), 
	sent_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE alert_logs (
	id SERIAL NOT NULL, 
	alert_type VARCHAR(50) NOT NULL, 
	severity VARCHAR(20), 
	is_critical BOOLEAN, 
	employee_id INTEGER, 
	employee_name VARCHAR(100), 
	description VARCHAR(500) NOT NULL, 
	details TEXT, 
	lat FLOAT, 
	lng FLOAT, 
	acknowledged_at TIMESTAMP WITHOUT TIME ZONE, 
	acknowledged_by INTEGER, 
	acknowledged_by_name VARCHAR(100), 
	snoozed_until TIMESTAMP WITHOUT TIME ZONE, 
	notes TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE approval_workflows (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	month INTEGER NOT NULL, 
	year INTEGER NOT NULL, 
	current_gross FLOAT, 
	proposed_gross FLOAT, 
	proposed_net FLOAT, 
	status VARCHAR(20), 
	current_step INTEGER, 
	total_steps INTEGER, 
	notes TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	reviewed_at TIMESTAMP WITHOUT TIME ZONE, 
	reviewed_by INTEGER, 
	PRIMARY KEY (id)
)

;


CREATE TABLE archived_documents (
	id SERIAL NOT NULL, 
	reference_code VARCHAR(30) NOT NULL, 
	title VARCHAR(200) NOT NULL, 
	file_path VARCHAR(300), 
	department VARCHAR(50), 
	employee_id INTEGER, 
	is_public BOOLEAN, 
	has_expiry_date BOOLEAN, 
	expiry_date DATE, 
	version INTEGER, 
	uploaded_by INTEGER, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	notes TEXT, 
	is_deleted BOOLEAN, 
	deleted_at TIMESTAMP WITHOUT TIME ZONE, 
	deleted_by INTEGER, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_archived_doc_ref_version UNIQUE (reference_code, version)
)

;


CREATE TABLE attendance_anomalies (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	log_date DATE NOT NULL, 
	anomaly_type VARCHAR(30) NOT NULL, 
	severity VARCHAR(10), 
	description VARCHAR(300), 
	details TEXT, 
	expected_value VARCHAR(50), 
	actual_value VARCHAR(50), 
	status VARCHAR(20), 
	reviewed_by INTEGER, 
	reviewed_at TIMESTAMP WITHOUT TIME ZONE, 
	review_notes VARCHAR(300), 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE attendance_policies (
	id SERIAL NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	department_id INTEGER, 
	shift_type_id INTEGER, 
	late_grace_minutes INTEGER, 
	early_leave_grace INTEGER, 
	max_late_minutes INTEGER, 
	min_work_hours FLOAT, 
	overtime_threshold_h FLOAT, 
	overtime_multiplier FLOAT, 
	auto_deduct_absence BOOLEAN, 
	allow_geofence_override BOOLEAN, 
	require_selfie BOOLEAN, 
	max_early_leave_min INTEGER, 
	is_active BOOLEAN, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE attendance_review_queue (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	record_id INTEGER, 
	flagged_reason VARCHAR(50) NOT NULL, 
	client_time TIMESTAMP WITHOUT TIME ZONE, 
	server_time TIMESTAMP WITHOUT TIME ZONE, 
	time_variance_minutes FLOAT, 
	department VARCHAR(50), 
	status VARCHAR(30) NOT NULL, 
	flagged_by VARCHAR(50), 
	flagged_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	reviewed_by INTEGER, 
	reviewed_at TIMESTAMP WITHOUT TIME ZONE, 
	admin_action VARCHAR(30), 
	adjusted_time TIMESTAMP WITHOUT TIME ZONE, 
	admin_notes TEXT, 
	reference_type VARCHAR(30), 
	is_superseded BOOLEAN, 
	superseded_by INTEGER, 
	notification_sent BOOLEAN, 
	PRIMARY KEY (id)
)

;


CREATE TABLE audit_logs (
	id SERIAL NOT NULL, 
	user_id INTEGER, 
	user_name VARCHAR(100), 
	action VARCHAR(30) NOT NULL, 
	entity_type VARCHAR(50), 
	entity_id INTEGER, 
	changes TEXT, 
	ip_address VARCHAR(45), 
	timestamp TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE backup_audit_logs (
	id SERIAL NOT NULL, 
	schedule_id INTEGER, 
	action VARCHAR(50) NOT NULL, 
	details TEXT, 
	user_id INTEGER, 
	user_name VARCHAR(100), 
	ip_address VARCHAR(50), 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE backup_restore_logs (
	id SERIAL NOT NULL, 
	backup_id INTEGER, 
	backup_filename VARCHAR(255), 
	restore_type VARCHAR(20), 
	status VARCHAR(20), 
	records_restored INTEGER, 
	tables_restored INTEGER, 
	files_restored INTEGER, 
	duration_seconds FLOAT, 
	error_message TEXT, 
	created_backup BOOLEAN, 
	performed_by INTEGER, 
	performed_by_name VARCHAR(100), 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE bank_payment_details (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	month INTEGER NOT NULL, 
	year INTEGER NOT NULL, 
	net_amount FLOAT, 
	iban VARCHAR(30), 
	bank_name VARCHAR(100), 
	status VARCHAR(20), 
	payment_date DATE, 
	transaction_id VARCHAR(100), 
	notes TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_bank_payment_month UNIQUE (employee_id, month, year)
)

;


CREATE TABLE biometric_credentials (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	credential_id VARCHAR(128) NOT NULL, 
	public_key TEXT, 
	device_info VARCHAR(100), 
	biometric_type VARCHAR(20), 
	is_active BOOLEAN, 
	last_used TIMESTAMP WITHOUT TIME ZONE, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (credential_id)
)

;


CREATE TABLE biometric_devices (
	id SERIAL NOT NULL, 
	company_id INTEGER NOT NULL, 
	serial_no VARCHAR(60) NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	device_model VARCHAR(30), 
	firmware_ver VARCHAR(20), 
	location VARCHAR(100), 
	branch_id INTEGER, 
	ip_address VARCHAR(50), 
	mac_address VARCHAR(30), 
	port INTEGER, 
	comm_password VARCHAR(20), 
	license_key VARCHAR(64), 
	api_key VARCHAR(64), 
	secret_key VARCHAR(128), 
	protocol VARCHAR(10), 
	is_active BOOLEAN, 
	is_online BOOLEAN, 
	last_online_at TIMESTAMP WITHOUT TIME ZONE, 
	last_sync TIMESTAMP WITHOUT TIME ZONE, 
	fp_capacity INTEGER, 
	fp_enrolled INTEGER, 
	face_capacity INTEGER, 
	face_enrolled INTEGER, 
	card_capacity INTEGER, 
	card_enrolled INTEGER, 
	txlog_capacity INTEGER, 
	txlog_used INTEGER, 
	records_pulled INTEGER, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	deleted_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (serial_no), 
	UNIQUE (license_key)
)

;


CREATE TABLE biotime_devices (
	id SERIAL NOT NULL, 
	company_id INTEGER, 
	serial_no VARCHAR(60) NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	device_type VARCHAR(30), 
	location VARCHAR(100), 
	ip_address VARCHAR(50), 
	mac_address VARCHAR(30), 
	firmware_ver VARCHAR(20), 
	api_key VARCHAR(64), 
	is_active BOOLEAN, 
	last_sync TIMESTAMP WITHOUT TIME ZONE, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	port INTEGER, 
	comm_password_encrypted TEXT, 
	protocol VARCHAR(10), 
	device_model VARCHAR(30), 
	manufacture_date DATE, 
	warranty_expiry DATE, 
	fp_capacity INTEGER, 
	fp_enrolled INTEGER, 
	face_capacity INTEGER, 
	face_enrolled INTEGER, 
	card_capacity INTEGER, 
	card_enrolled INTEGER, 
	txlog_capacity INTEGER, 
	txlog_used INTEGER, 
	assigned_departments TEXT, 
	assigned_employees TEXT, 
	access_mode VARCHAR(20), 
	door_relay_enabled BOOLEAN, 
	anti_passback_enabled BOOLEAN, 
	auto_sync_enabled BOOLEAN, 
	sync_interval INTEGER, 
	sync_window_start VARCHAR(5), 
	sync_window_end VARCHAR(5), 
	records_pulled INTEGER, 
	sync_error_log TEXT, 
	is_online BOOLEAN, 
	last_online_at TIMESTAMP WITHOUT TIME ZONE, 
	uptime_percent_24h FLOAT, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (serial_no)
)

;


CREATE TABLE company_admins (
	id SERIAL NOT NULL, 
	company_id INTEGER NOT NULL, 
	username VARCHAR(60) NOT NULL, 
	password_hash VARCHAR(256) NOT NULL, 
	full_name VARCHAR(100), 
	email VARCHAR(120), 
	phone VARCHAR(20), 
	role VARCHAR(20), 
	is_active BOOLEAN, 
	last_login TIMESTAMP WITHOUT TIME ZONE, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (username)
)

;


CREATE TABLE custom_rule (
	id SERIAL NOT NULL, 
	rule_name VARCHAR(200) NOT NULL, 
	rule_description TEXT, 
	metric VARCHAR(100) NOT NULL, 
	condition VARCHAR(50), 
	threshold FLOAT, 
	rule_params TEXT, 
	alert_message TEXT, 
	severity VARCHAR(20), 
	notification_method VARCHAR(50), 
	is_active BOOLEAN, 
	created_by INTEGER, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE department_announcements (
	id SERIAL NOT NULL, 
	department_id INTEGER NOT NULL, 
	message TEXT NOT NULL, 
	priority VARCHAR(10), 
	delivery_method VARCHAR(50), 
	scheduled_at TIMESTAMP WITHOUT TIME ZONE, 
	sent_at TIMESTAMP WITHOUT TIME ZONE, 
	sent_by INTEGER, 
	target_type VARCHAR(20), 
	target_ids TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE department_certifications (
	id SERIAL NOT NULL, 
	department_id INTEGER NOT NULL, 
	certification VARCHAR(100) NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE department_transfers (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	from_department_id INTEGER, 
	to_department_id INTEGER NOT NULL, 
	transfer_date DATE NOT NULL, 
	reason_type VARCHAR(30), 
	reason_notes TEXT, 
	status VARCHAR(20), 
	approved_by_manager BOOLEAN, 
	approved_by_hr BOOLEAN, 
	manager_approved_at TIMESTAMP WITHOUT TIME ZONE, 
	hr_approved_at TIMESTAMP WITHOUT TIME ZONE, 
	executed_at TIMESTAMP WITHOUT TIME ZONE, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE dept_alert_recipients (
	department_id INTEGER NOT NULL, 
	employee_id INTEGER NOT NULL, 
	PRIMARY KEY (department_id, employee_id)
)

;


CREATE TABLE dept_required_certs (
	department_id INTEGER NOT NULL, 
	certification VARCHAR(100) NOT NULL, 
	PRIMARY KEY (department_id, certification)
)

;


CREATE TABLE employee_certifications (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	cert_type VARCHAR(100) NOT NULL, 
	cert_number VARCHAR(50), 
	issuing_body VARCHAR(200) NOT NULL, 
	issue_date DATE NOT NULL, 
	expiry_date DATE, 
	is_valid BOOLEAN, 
	cert_file VARCHAR(200), 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE employee_children (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	full_name VARCHAR(100) NOT NULL, 
	birth_date DATE NOT NULL, 
	relation VARCHAR(30), 
	is_student BOOLEAN, 
	is_disabled BOOLEAN, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE employee_delegations (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	delegation_type VARCHAR(100) NOT NULL, 
	delegation_body VARCHAR(200) NOT NULL, 
	role VARCHAR(100), 
	start_date DATE NOT NULL, 
	end_date DATE, 
	decision_number VARCHAR(50), 
	notes TEXT, 
	is_active BOOLEAN, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE employee_disciplinary_actions (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	action_type VARCHAR(50) NOT NULL, 
	description TEXT NOT NULL, 
	decision_number VARCHAR(50), 
	decision_date DATE, 
	issued_by INTEGER, 
	duration_days INTEGER, 
	status VARCHAR(20), 
	appeal_notes TEXT, 
	closed_at TIMESTAMP WITHOUT TIME ZONE, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE employee_documents (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	doc_type VARCHAR(50) NOT NULL, 
	doc_name VARCHAR(100) NOT NULL, 
	file_path VARCHAR(300) NOT NULL, 
	file_size INTEGER, 
	mime_type VARCHAR(50), 
	expiry_date DATE, 
	is_verified BOOLEAN, 
	notes TEXT, 
	uploaded_by INTEGER, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE employee_extended (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	national_id VARCHAR(20), 
	passport_number VARCHAR(30), 
	id_expiry_date DATE, 
	id_issuing_authority VARCHAR(100), 
	id_verified BOOLEAN, 
	personal_phone VARCHAR(20), 
	work_phone VARCHAR(20), 
	personal_email VARCHAR(120), 
	work_email VARCHAR(120), 
	permanent_address TEXT, 
	current_address TEXT, 
	emergency_name VARCHAR(100), 
	emergency_phone VARCHAR(20), 
	emergency_relation VARCHAR(30), 
	bank_name VARCHAR(100), 
	bank_account_name VARCHAR(100), 
	iban VARCHAR(34), 
	bank_account_type VARCHAR(20), 
	bank_branch VARCHAR(100), 
	bank_account_verified BOOLEAN, 
	marital_status VARCHAR(20), 
	spouse_name VARCHAR(100), 
	dependent_children INTEGER, 
	grade_id INTEGER, 
	job_classification VARCHAR(50), 
	career_path VARCHAR(100), 
	contract_type VARCHAR(30), 
	gov_file_number VARCHAR(50), 
	gov_central_emp_id VARCHAR(50), 
	gov_region VARCHAR(50), 
	gov_sector VARCHAR(100), 
	gov_parent_institution VARCHAR(200), 
	gov_supervisory_body VARCHAR(200), 
	clearance_level VARCHAR(30), 
	clearance_date DATE, 
	clearance_expiry DATE, 
	clearance_authority VARCHAR(100), 
	social_security_number VARCHAR(30), 
	social_security_start DATE, 
	social_security_rate FLOAT, 
	accumulated_contributions FLOAT, 
	health_insurance_level VARCHAR(30), 
	health_insurance_dependents INTEGER, 
	health_insurance_premium FLOAT, 
	life_insurance_coverage FLOAT, 
	life_insurance_beneficiary VARCHAR(100), 
	life_insurance_premium FLOAT, 
	injury_insurance_coverage FLOAT, 
	retirement_age INTEGER, 
	pension_rate FLOAT, 
	years_of_service FLOAT, 
	expected_pension FLOAT, 
	annual_leave_days INTEGER, 
	sick_leave_days INTEGER, 
	maternity_leave_days INTEGER, 
	paternity_leave_days INTEGER, 
	marriage_leave_days INTEGER, 
	hajj_leave_days INTEGER, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (employee_id), 
	UNIQUE (national_id), 
	UNIQUE (gov_file_number)
)

;


CREATE TABLE employee_leave_balances (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	leave_type_id INTEGER NOT NULL, 
	year INTEGER NOT NULL, 
	opening_balance FLOAT, 
	total_days FLOAT, 
	used_days FLOAT, 
	pending_days FLOAT, 
	remaining_days FLOAT, 
	carried_over FLOAT, 
	carry_expiry_date DATE, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_emp_leave_year UNIQUE (employee_id, leave_type_id, year)
)

;


CREATE TABLE employee_leave_requests (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	leave_type_id INTEGER NOT NULL, 
	start_date DATE NOT NULL, 
	end_date DATE NOT NULL, 
	total_days FLOAT NOT NULL, 
	reason TEXT, 
	status VARCHAR(20), 
	reviewed_by INTEGER, 
	review_comment TEXT, 
	reviewed_at TIMESTAMP WITHOUT TIME ZONE, 
	attachment VARCHAR(200), 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE employee_patterns (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	avg_clock_in_minutes FLOAT, 
	std_clock_in_minutes FLOAT, 
	avg_clock_out_minutes FLOAT, 
	std_clock_out_minutes FLOAT, 
	avg_break_minutes FLOAT, 
	std_break_minutes FLOAT, 
	usual_device_ids TEXT, 
	avg_hours_worked FLOAT, 
	std_hours_worked FLOAT, 
	total_samples INTEGER, 
	last_updated TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (employee_id)
)

;


CREATE TABLE employee_performance (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	evaluation_year INTEGER NOT NULL, 
	evaluation_period VARCHAR(20), 
	overall_rating VARCHAR(30), 
	score FLOAT, 
	evaluated_by INTEGER, 
	comments TEXT, 
	goals_next_period TEXT, 
	status VARCHAR(20), 
	completed_at TIMESTAMP WITHOUT TIME ZONE, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_emp_eval_period UNIQUE (employee_id, evaluation_year, evaluation_period)
)

;


CREATE TABLE employee_permissions (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	permission_id INTEGER NOT NULL, 
	PRIMARY KEY (id)
)

;


CREATE TABLE employee_profiles (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	job_title VARCHAR(100), 
	hire_date DATE, 
	marital_status VARCHAR(20), 
	contract_expiry DATE, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (employee_id)
)

;


CREATE TABLE employee_promotions (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	from_grade_id INTEGER, 
	to_grade_id INTEGER NOT NULL, 
	from_grade_name VARCHAR(100), 
	to_grade_name VARCHAR(100) NOT NULL, 
	from_salary FLOAT, 
	to_salary FLOAT, 
	decision_number VARCHAR(50), 
	decision_date DATE, 
	effective_date DATE NOT NULL, 
	approved_by INTEGER, 
	justification TEXT, 
	status VARCHAR(20), 
	notes TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE employee_qualifications (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	level VARCHAR(30) NOT NULL, 
	specialization VARCHAR(100) NOT NULL, 
	institution VARCHAR(200) NOT NULL, 
	graduation_year INTEGER NOT NULL, 
	grade VARCHAR(30), 
	is_foreign BOOLEAN, 
	equivalency_file VARCHAR(200), 
	certificate_file VARCHAR(200), 
	is_verified BOOLEAN, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE employee_training (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	course_name VARCHAR(200) NOT NULL, 
	provider VARCHAR(200) NOT NULL, 
	start_date DATE, 
	end_date DATE, 
	duration_hours FLOAT, 
	cert_earned BOOLEAN, 
	cert_file VARCHAR(200), 
	is_government_required BOOLEAN, 
	status VARCHAR(20), 
	notes TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE employees_government (
	id SERIAL NOT NULL, 
	username VARCHAR(20) NOT NULL, 
	password_hash VARCHAR(256) NOT NULL, 
	role VARCHAR(10), 
	is_active BOOLEAN, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	first_name VARCHAR(50) NOT NULL, 
	second_name VARCHAR(50) NOT NULL, 
	third_name VARCHAR(50), 
	fourth_name VARCHAR(50), 
	family_name VARCHAR(50) NOT NULL, 
	national_id VARCHAR(20) NOT NULL, 
	national_id_verified BOOLEAN, 
	date_of_birth DATE NOT NULL, 
	gender VARCHAR(10) NOT NULL, 
	marital_status VARCHAR(20), 
	passport_number VARCHAR(30), 
	passport_expiry DATE, 
	id_expiry_date DATE, 
	id_issuing_authority VARCHAR(100), 
	personal_phone VARCHAR(20), 
	work_phone VARCHAR(20), 
	personal_email VARCHAR(120), 
	work_email VARCHAR(120), 
	permanent_address TEXT, 
	current_address TEXT, 
	residence_province VARCHAR(50), 
	email_encrypted TEXT, 
	phone_encrypted TEXT, 
	base_salary_encrypted TEXT, 
	emergency_name VARCHAR(100), 
	emergency_phone VARCHAR(20), 
	emergency_relation VARCHAR(30), 
	profile_photo VARCHAR(200), 
	department VARCHAR(50) NOT NULL, 
	department_id INTEGER, 
	branch_id INTEGER, 
	manager_id INTEGER, 
	job_title VARCHAR(100), 
	employment_type VARCHAR(20), 
	contract_type VARCHAR(30), 
	hire_date DATE, 
	contract_end_date DATE, 
	no_end_date BOOLEAN, 
	job_classification VARCHAR(50), 
	career_path VARCHAR(100), 
	category VARCHAR(30), 
	grade_id INTEGER, 
	housing_allowance FLOAT, 
	transport_allowance FLOAT, 
	responsibility_allowance FLOAT, 
	hazard_allowance FLOAT, 
	other_allowances TEXT, 
	payment_method VARCHAR(20), 
	bank_name VARCHAR(100), 
	bank_account_name VARCHAR(100), 
	bank_account_number VARCHAR(30), 
	iban VARCHAR(34), 
	bank_account_type VARCHAR(20), 
	bank_branch VARCHAR(100), 
	bank_account_verified BOOLEAN, 
	spouse_name VARCHAR(100), 
	dependent_children INTEGER, 
	gov_file_number VARCHAR(50), 
	gov_central_emp_id VARCHAR(50), 
	gov_region VARCHAR(50), 
	gov_sector VARCHAR(100), 
	gov_parent_institution VARCHAR(200), 
	gov_supervisory_body VARCHAR(200), 
	administrative_region VARCHAR(100), 
	work_region VARCHAR(100), 
	clearance_level VARCHAR(30), 
	clearance_date DATE, 
	clearance_expiry DATE, 
	clearance_authority VARCHAR(100), 
	social_security_number VARCHAR(30), 
	social_security_start DATE, 
	social_security_rate FLOAT, 
	accumulated_contributions FLOAT, 
	health_insurance_level VARCHAR(30), 
	health_insurance_dependents INTEGER, 
	health_insurance_premium FLOAT, 
	life_insurance_coverage FLOAT, 
	life_insurance_beneficiary VARCHAR(100), 
	life_insurance_premium FLOAT, 
	injury_insurance_coverage FLOAT, 
	retirement_age INTEGER, 
	pension_rate FLOAT, 
	years_of_service FLOAT, 
	expected_pension FLOAT, 
	annual_leave_days INTEGER, 
	sick_leave_days INTEGER, 
	maternity_leave_days INTEGER, 
	paternity_leave_days INTEGER, 
	marriage_leave_days INTEGER, 
	hajj_leave_days INTEGER, 
	unpaid_leave_days INTEGER, 
	carried_over_days FLOAT, 
	used_leave_days FLOAT, 
	remaining_leave_days FLOAT, 
	permission_level VARCHAR(30), 
	force_password_change BOOLEAN, 
	two_factor_enabled BOOLEAN, 
	password_changed_at TIMESTAMP WITHOUT TIME ZONE, 
	device_id VARCHAR(120), 
	deleted_at TIMESTAMP WITHOUT TIME ZONE, 
	deleted_by INTEGER, 
	delete_reason VARCHAR(300), 
	biotime_emp_id INTEGER, 
	assigned_devices TEXT, 
	last_sync TIMESTAMP WITHOUT TIME ZONE, 
	fp_enrolled BOOLEAN, 
	face_enrolled BOOLEAN, 
	sync_status VARCHAR(20), 
	PRIMARY KEY (id), 
	UNIQUE (username), 
	UNIQUE (gov_file_number)
)

;


CREATE TABLE geofence_events (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	zone_id INTEGER NOT NULL, 
	event_type VARCHAR(20) NOT NULL, 
	lat FLOAT, 
	lng FLOAT, 
	accuracy FLOAT, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE gps_logs (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	latitude FLOAT, 
	latitude_enc TEXT, 
	longitude FLOAT, 
	longitude_enc TEXT, 
	accuracy FLOAT, 
	battery FLOAT, 
	source VARCHAR(20), 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE gps_tracking_sessions (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	device_id VARCHAR(120), 
	ip_address VARCHAR(50), 
	user_agent VARCHAR(300), 
	is_active BOOLEAN, 
	started_at TIMESTAMP WITHOUT TIME ZONE, 
	ended_at TIMESTAMP WITHOUT TIME ZONE, 
	last_ping_at TIMESTAMP WITHOUT TIME ZONE, 
	total_updates INTEGER, 
	PRIMARY KEY (id)
)

;


CREATE TABLE leave_balances (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	leave_type VARCHAR(50) NOT NULL, 
	total_days FLOAT, 
	used_days FLOAT, 
	remaining_days FLOAT, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_employee_leave_type UNIQUE (employee_id, leave_type)
)

;


CREATE TABLE leave_requests (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	request_type VARCHAR(30) NOT NULL, 
	start_date DATE NOT NULL, 
	end_date DATE, 
	reason TEXT, 
	status VARCHAR(20), 
	approved_by INTEGER, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	approved_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE location_audit_logs (
	id SERIAL NOT NULL, 
	user_id INTEGER NOT NULL, 
	user_name VARCHAR(100), 
	action VARCHAR(50) NOT NULL, 
	target_employee_id INTEGER, 
	target_name VARCHAR(100), 
	ip_address VARCHAR(50), 
	details TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE notifications (
	id SERIAL NOT NULL, 
	employee_id INTEGER, 
	title VARCHAR(100) NOT NULL, 
	message TEXT NOT NULL, 
	ntype VARCHAR(30), 
	icon VARCHAR(30), 
	url VARCHAR(200), 
	is_read BOOLEAN, 
	is_global BOOLEAN, 
	type VARCHAR(50), 
	reference_id INTEGER, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE outing_requests (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	outing_date DATE, 
	reason VARCHAR(200), 
	status VARCHAR(20), 
	approved_by INTEGER, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	approved_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE payroll_audit_logs (
	id SERIAL NOT NULL, 
	action VARCHAR(50) NOT NULL, 
	employee_id INTEGER, 
	changed_by INTEGER, 
	details TEXT, 
	old_value TEXT, 
	new_value TEXT, 
	ip_address VARCHAR(45), 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE payroll_records (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	month INTEGER NOT NULL, 
	year INTEGER NOT NULL, 
	base_salary FLOAT, 
	housing_allowance FLOAT, 
	transport_allowance FLOAT, 
	other_allowances FLOAT, 
	total_allowances FLOAT, 
	overtime_hours FLOAT, 
	overtime_pay FLOAT, 
	gross_salary FLOAT, 
	late_minutes INTEGER, 
	late_deduction FLOAT, 
	absent_days INTEGER, 
	absent_deduction FLOAT, 
	other_deductions FLOAT, 
	total_deductions FLOAT, 
	income_tax FLOAT, 
	social_security FLOAT, 
	total_tax FLOAT, 
	net_salary FLOAT, 
	payment_method VARCHAR(20), 
	status VARCHAR(20), 
	notes TEXT, 
	calculated_at TIMESTAMP WITHOUT TIME ZONE, 
	approved_at TIMESTAMP WITHOUT TIME ZONE, 
	approved_by INTEGER, 
	paid_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_employee_payroll_month UNIQUE (employee_id, month, year)
)

;


CREATE TABLE photo_verifications (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	photo_path VARCHAR(300) NOT NULL, 
	lat FLOAT, 
	lng FLOAT, 
	accuracy FLOAT, 
	verified BOOLEAN, 
	verified_by INTEGER, 
	notes TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE promotion_eligibility (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	current_grade_id INTEGER, 
	target_grade_id INTEGER, 
	min_service_met BOOLEAN, 
	performance_met BOOLEAN, 
	qualifications_met BOOLEAN, 
	conduct_met BOOLEAN, 
	total_requirements INTEGER, 
	completed_requirements INTEGER, 
	expected_date DATE, 
	last_evaluated_at TIMESTAMP WITHOUT TIME ZONE, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE qr_tokens (
	id SERIAL NOT NULL, 
	token_hash VARCHAR(64) NOT NULL, 
	employee_id INTEGER, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	used_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE rbac_audit_logs (
	id SERIAL NOT NULL, 
	action VARCHAR(50) NOT NULL, 
	entity_type VARCHAR(50) NOT NULL, 
	entity_id INTEGER, 
	changes TEXT, 
	ip_address VARCHAR(45), 
	user_agent VARCHAR(200), 
	performed_by INTEGER, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE rbac_delegations (
	id SERIAL NOT NULL, 
	delegator_id INTEGER NOT NULL, 
	delegate_id INTEGER NOT NULL, 
	permission_ids TEXT NOT NULL, 
	start_date TIMESTAMP WITHOUT TIME ZONE, 
	end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	reason TEXT, 
	is_active BOOLEAN, 
	revoked_at TIMESTAMP WITHOUT TIME ZONE, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE rbac_permission_requests (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	requested_perms TEXT NOT NULL, 
	justification TEXT, 
	duration_days INTEGER, 
	risk_level VARCHAR(20), 
	status VARCHAR(20), 
	reviewed_by INTEGER, 
	review_comment TEXT, 
	reviewed_at TIMESTAMP WITHOUT TIME ZONE, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE rbac_roles (
	id SERIAL NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	name_ar VARCHAR(100), 
	description TEXT, 
	parent_id INTEGER, 
	scope VARCHAR(20), 
	is_system BOOLEAN, 
	is_active BOOLEAN, 
	risk_level VARCHAR(20), 
	max_assignees INTEGER, 
	created_by INTEGER, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (name)
)

;


CREATE TABLE refresh_tokens (
	id SERIAL NOT NULL, 
	user_id INTEGER NOT NULL, 
	token_hash VARCHAR(128) NOT NULL, 
	expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	is_revoked BOOLEAN, 
	device_info VARCHAR(200), 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	revoked_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE report_corrections (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	log_date DATE NOT NULL, 
	correction_type VARCHAR(30) NOT NULL, 
	original_value VARCHAR(50), 
	corrected_value VARCHAR(50), 
	reason TEXT NOT NULL, 
	document_path VARCHAR(300), 
	status VARCHAR(20), 
	reviewed_by INTEGER, 
	reviewed_at TIMESTAMP WITHOUT TIME ZONE, 
	review_notes TEXT, 
	created_by INTEGER, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE salary_advances (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	amount FLOAT NOT NULL, 
	installments_count INTEGER, 
	installment_amount FLOAT, 
	installments_paid JSON, 
	reason VARCHAR(200), 
	auto_deduct BOOLEAN, 
	status VARCHAR(20), 
	notes TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	settled_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE salary_slip_archives (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	month INTEGER NOT NULL, 
	year INTEGER NOT NULL, 
	base_salary_snapshot TEXT, 
	deductions FLOAT, 
	overtime_pay FLOAT, 
	net_salary FLOAT, 
	archived_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_employee_month_year UNIQUE (employee_id, month, year)
)

;


CREATE TABLE scheduled_reports (
	id SERIAL NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	frequency VARCHAR(20) NOT NULL, 
	day_of_month INTEGER, 
	day_of_week INTEGER, 
	time_hour INTEGER NOT NULL, 
	time_minute INTEGER NOT NULL, 
	format_type VARCHAR(20), 
	recipients_json TEXT, 
	department_ids TEXT, 
	is_active BOOLEAN, 
	last_run_at TIMESTAMP WITHOUT TIME ZONE, 
	last_status VARCHAR(20), 
	next_run_at TIMESTAMP WITHOUT TIME ZONE, 
	created_by INTEGER, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE shift_coverage_rules (
	id SERIAL NOT NULL, 
	shift_type_id INTEGER NOT NULL, 
	department VARCHAR(50), 
	day_of_week INTEGER, 
	min_staff INTEGER NOT NULL, 
	max_staff INTEGER, 
	is_active BOOLEAN, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE shift_schedules (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	shift_type_id INTEGER NOT NULL, 
	scheduled_date DATE NOT NULL, 
	status VARCHAR(20), 
	notes VARCHAR(200), 
	overtime_hours FLOAT, 
	created_by INTEGER, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	original_employee_id INTEGER, 
	conflict_status VARCHAR(20), 
	substituted_by INTEGER, 
	substituted_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE tracking_policies (
	id SERIAL NOT NULL, 
	employee_id INTEGER, 
	policy_type VARCHAR(30), 
	tracking_enabled BOOLEAN, 
	work_hours_only BOOLEAN, 
	allow_opt_out BOOLEAN, 
	opted_out BOOLEAN, 
	data_retention_days INTEGER, 
	notify_on_entry BOOLEAN, 
	notify_on_exit BOOLEAN, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE trusted_devices (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	device_name VARCHAR(100) NOT NULL, 
	device_fingerprint VARCHAR(128) NOT NULL, 
	device_os VARCHAR(30), 
	ip_address VARCHAR(50), 
	is_trusted BOOLEAN, 
	last_used TIMESTAMP WITHOUT TIME ZONE, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE trusted_locations (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	lat FLOAT NOT NULL, 
	lng FLOAT NOT NULL, 
	radius FLOAT, 
	address VARCHAR(300), 
	is_active BOOLEAN, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE user_preferences (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	theme VARCHAR(10), 
	language VARCHAR(5), 
	notifications_enabled BOOLEAN, 
	email_notifications BOOLEAN, 
	sms_notifications BOOLEAN, 
	share_location BOOLEAN, 
	allow_biometric BOOLEAN, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (employee_id)
)

;


CREATE TABLE approval_steps (
	id SERIAL NOT NULL, 
	workflow_id INTEGER NOT NULL, 
	step_order INTEGER NOT NULL, 
	approver_id INTEGER, 
	approver_name VARCHAR(100), 
	status VARCHAR(20), 
	comment TEXT, 
	acted_at TIMESTAMP WITHOUT TIME ZONE, 
	acted_by INTEGER, 
	PRIMARY KEY (id)
)

;


CREATE TABLE attendance_logs (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	company_id INTEGER, 
	device_id INTEGER, 
	log_date DATE NOT NULL, 
	clock_in TIMESTAMP WITHOUT TIME ZONE, 
	clock_out TIMESTAMP WITHOUT TIME ZONE, 
	lat_in FLOAT, 
	lat_in_enc TEXT, 
	lng_in FLOAT, 
	lng_in_enc TEXT, 
	lat_out FLOAT, 
	lat_out_enc TEXT, 
	lng_out FLOAT, 
	lng_out_enc TEXT, 
	distance_in INTEGER, 
	status VARCHAR(20), 
	selfie_data TEXT, 
	late_minutes INTEGER, 
	early_leave_minutes INTEGER, 
	overtime_minutes INTEGER, 
	is_inside_geofence BOOLEAN, 
	geofence_violated_at TIMESTAMP WITHOUT TIME ZONE, 
	has_exit_permission BOOLEAN, 
	override_reason VARCHAR(200), 
	policy_id INTEGER, 
	device_serial VARCHAR(60), 
	PRIMARY KEY (id)
)

;


CREATE TABLE deduction_records (
	id SERIAL NOT NULL, 
	payroll_record_id INTEGER, 
	employee_id INTEGER NOT NULL, 
	deduction_type VARCHAR(50) NOT NULL, 
	label VARCHAR(100) NOT NULL, 
	amount FLOAT, 
	reason TEXT, 
	days_count INTEGER, 
	minutes_count INTEGER, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE dept_allowed_devices (
	department_id INTEGER NOT NULL, 
	device_id INTEGER NOT NULL, 
	PRIMARY KEY (department_id, device_id)
)

;


CREATE TABLE device_event_logs (
	id SERIAL NOT NULL, 
	device_id INTEGER NOT NULL, 
	event_type VARCHAR(30) NOT NULL, 
	message VARCHAR(300), 
	error_code VARCHAR(20), 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE device_health_snapshots (
	id SERIAL NOT NULL, 
	device_id INTEGER NOT NULL, 
	is_online BOOLEAN, 
	ping_ms FLOAT, 
	fp_enrolled INTEGER, 
	face_enrolled INTEGER, 
	txlog_used INTEGER, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE device_sync_logs (
	id SERIAL NOT NULL, 
	company_id INTEGER NOT NULL, 
	device_id INTEGER NOT NULL, 
	event_type VARCHAR(30) NOT NULL, 
	direction VARCHAR(10), 
	payload TEXT, 
	status VARCHAR(20), 
	error_msg TEXT, 
	ip_address VARCHAR(50), 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE document_audit_logs (
	id SERIAL NOT NULL, 
	document_id INTEGER NOT NULL, 
	action VARCHAR(20) NOT NULL, 
	performed_by INTEGER, 
	performed_at TIMESTAMP WITHOUT TIME ZONE, 
	details TEXT, 
	description VARCHAR(300), 
	PRIMARY KEY (id)
)

;


CREATE TABLE rbac_employee_roles (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	role_id INTEGER NOT NULL, 
	is_primary BOOLEAN, 
	assignment_type VARCHAR(20), 
	effective_date DATE, 
	expiry_date DATE, 
	season_months VARCHAR(50), 
	shift_type_ids VARCHAR(100), 
	notes TEXT, 
	assigned_by INTEGER, 
	assigned_at TIMESTAMP WITHOUT TIME ZONE, 
	is_active BOOLEAN, 
	revoked_at TIMESTAMP WITHOUT TIME ZONE, 
	revoked_by INTEGER, 
	PRIMARY KEY (id)
)

;


CREATE TABLE role_departments (
	role_id INTEGER NOT NULL, 
	department_id INTEGER NOT NULL, 
	PRIMARY KEY (role_id, department_id)
)

;


CREATE TABLE role_permissions (
	role_id INTEGER NOT NULL, 
	permission_id INTEGER NOT NULL, 
	PRIMARY KEY (role_id, permission_id)
)

;


CREATE TABLE salary_components (
	id SERIAL NOT NULL, 
	payroll_record_id INTEGER, 
	employee_id INTEGER NOT NULL, 
	component_type VARCHAR(50) NOT NULL, 
	label VARCHAR(100) NOT NULL, 
	amount FLOAT, 
	is_earning BOOLEAN, 
	description TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE shift_exceptions (
	id SERIAL NOT NULL, 
	employee_id INTEGER NOT NULL, 
	shift_schedule_id INTEGER, 
	exception_date DATE NOT NULL, 
	exception_type VARCHAR(20) NOT NULL, 
	reason VARCHAR(300), 
	resolved_by INTEGER, 
	resolved_at TIMESTAMP WITHOUT TIME ZONE, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE shift_swap_requests (
	id SERIAL NOT NULL, 
	requester_id INTEGER NOT NULL, 
	target_id INTEGER NOT NULL, 
	req_sched_id INTEGER, 
	tgt_sched_id INTEGER, 
	scheduled_date DATE, 
	swap_type VARCHAR(20), 
	substitute_employee_id INTEGER, 
	reason TEXT, 
	status VARCHAR(30), 
	target_response VARCHAR(20), 
	admin_notes VARCHAR(300), 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;

-- ---- indexes (incl. UNIQUE indexes backing FK targets) ----
CREATE INDEX ix_anomaly_log_detected_date ON anomaly_log (detected_date);
CREATE INDEX ix_anomaly_log_employee_id ON anomaly_log (employee_id);
CREATE UNIQUE INDEX ix_document_references_reference_code ON document_references (reference_code);
CREATE INDEX ix_employees_department ON employees (department);
CREATE INDEX ix_employees_full_name ON employees (full_name);
CREATE INDEX ix_employees_is_active ON employees (is_active);
CREATE INDEX ix_employees_role ON employees (role);
CREATE UNIQUE INDEX ix_employees_username ON employees (username);
CREATE INDEX ix_holiday_calendar_date ON holiday_calendar (date);
CREATE INDEX ix_model_performance_log_model_key ON model_performance_log (model_key);
CREATE UNIQUE INDEX ix_model_registry_model_key ON model_registry (model_key);
CREATE INDEX idx_prediction_lookup ON prediction_result (employee_id, prediction_type, prediction_date);
CREATE INDEX ix_prediction_result_employee_id ON prediction_result (employee_id);
CREATE INDEX ix_prediction_result_prediction_date ON prediction_result (prediction_date);
CREATE INDEX ix_prediction_result_prediction_type ON prediction_result (prediction_type);
CREATE INDEX idx_risk_lookup ON risk_assessment (employee_id, assessment_type, assessment_date);
CREATE INDEX ix_risk_assessment_employee_id ON risk_assessment (employee_id);
CREATE UNIQUE INDEX ix_employees_government_national_id ON employees_government (national_id);
CREATE UNIQUE INDEX ix_qr_tokens_token_hash ON qr_tokens (token_hash);
CREATE UNIQUE INDEX ix_refresh_tokens_token_hash ON refresh_tokens (token_hash);
CREATE INDEX ix_refresh_tokens_user_id ON refresh_tokens (user_id);
CREATE INDEX ix_attendance_logs_employee_date ON attendance_logs (employee_id, log_date);
CREATE INDEX ix_attendance_logs_employee_id ON attendance_logs (employee_id);
CREATE INDEX ix_attendance_logs_log_date ON attendance_logs (log_date);
CREATE INDEX ix_attendance_logs_status ON attendance_logs (status);
CREATE INDEX ix_document_audit_logs_document_id ON document_audit_logs (document_id);
CREATE INDEX ix_document_audit_logs_performed_at ON document_audit_logs (performed_at);

-- ---- deferred foreign keys ----
ALTER TABLE "departments" ADD CONSTRAINT "fk_departments_deputy_id" FOREIGN KEY ("deputy_id") REFERENCES "employees" ("id");
ALTER TABLE "departments" ADD CONSTRAINT "fk_departments_manager_id" FOREIGN KEY ("manager_id") REFERENCES "employees" ("id");
ALTER TABLE "departments" ADD CONSTRAINT "fk_departments_parent_id" FOREIGN KEY ("parent_id") REFERENCES "departments" ("id");
ALTER TABLE "departments" ADD CONSTRAINT "fk_departments_default_shift_id" FOREIGN KEY ("default_shift_id") REFERENCES "shift_types" ("id");
ALTER TABLE "employee_grades" ADD CONSTRAINT "fk_employee_grades_next_grade_id" FOREIGN KEY ("next_grade_id") REFERENCES "employee_grades" ("id");
ALTER TABLE "employees" ADD CONSTRAINT "fk_employees_department_id" FOREIGN KEY ("department_id") REFERENCES "departments" ("id");
ALTER TABLE "employees" ADD CONSTRAINT "fk_employees_shift_type_id" FOREIGN KEY ("shift_type_id") REFERENCES "shift_types" ("id");
ALTER TABLE "employees" ADD CONSTRAINT "fk_employees_deleted_by" FOREIGN KEY ("deleted_by") REFERENCES "employees" ("id");
ALTER TABLE "employees" ADD CONSTRAINT "fk_employees_company_id" FOREIGN KEY ("company_id") REFERENCES "companies" ("id");
ALTER TABLE "employees" ADD CONSTRAINT "fk_employees_manager_id" FOREIGN KEY ("manager_id") REFERENCES "employees" ("id");
ALTER TABLE "employees" ADD CONSTRAINT "fk_employees_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches" ("id");
ALTER TABLE "alert_logs" ADD CONSTRAINT "fk_alert_logs_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "approval_workflows" ADD CONSTRAINT "fk_approval_workflows_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "approval_workflows" ADD CONSTRAINT "fk_approval_workflows_reviewed_by" FOREIGN KEY ("reviewed_by") REFERENCES "employees" ("id");
ALTER TABLE "archived_documents" ADD CONSTRAINT "fk_archived_documents_uploaded_by" FOREIGN KEY ("uploaded_by") REFERENCES "employees" ("id") ON DELETE SET NULL;
ALTER TABLE "archived_documents" ADD CONSTRAINT "fk_archived_documents_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") ON DELETE SET NULL;
ALTER TABLE "archived_documents" ADD CONSTRAINT "fk_archived_documents_reference_code" FOREIGN KEY ("reference_code") REFERENCES "document_references" ("reference_code");
ALTER TABLE "archived_documents" ADD CONSTRAINT "fk_archived_documents_deleted_by" FOREIGN KEY ("deleted_by") REFERENCES "employees" ("id") ON DELETE SET NULL;
ALTER TABLE "attendance_anomalies" ADD CONSTRAINT "fk_attendance_anomalies_reviewed_by" FOREIGN KEY ("reviewed_by") REFERENCES "employees" ("id");
ALTER TABLE "attendance_anomalies" ADD CONSTRAINT "fk_attendance_anomalies_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "attendance_policies" ADD CONSTRAINT "fk_attendance_policies_department_id" FOREIGN KEY ("department_id") REFERENCES "departments" ("id");
ALTER TABLE "attendance_policies" ADD CONSTRAINT "fk_attendance_policies_shift_type_id" FOREIGN KEY ("shift_type_id") REFERENCES "shift_types" ("id");
ALTER TABLE "attendance_review_queue" ADD CONSTRAINT "fk_attendance_review_queue_reviewed_by" FOREIGN KEY ("reviewed_by") REFERENCES "employees" ("id");
ALTER TABLE "attendance_review_queue" ADD CONSTRAINT "fk_attendance_review_queue_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "audit_logs" ADD CONSTRAINT "fk_audit_logs_user_id" FOREIGN KEY ("user_id") REFERENCES "employees" ("id");
ALTER TABLE "backup_audit_logs" ADD CONSTRAINT "fk_backup_audit_logs_schedule_id" FOREIGN KEY ("schedule_id") REFERENCES "backup_schedules" ("id");
ALTER TABLE "backup_restore_logs" ADD CONSTRAINT "fk_backup_restore_logs_backup_id" FOREIGN KEY ("backup_id") REFERENCES "backup_metadata" ("id");
ALTER TABLE "bank_payment_details" ADD CONSTRAINT "fk_bank_payment_details_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "biometric_credentials" ADD CONSTRAINT "fk_biometric_credentials_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "biometric_devices" ADD CONSTRAINT "fk_biometric_devices_company_id" FOREIGN KEY ("company_id") REFERENCES "companies" ("id");
ALTER TABLE "biometric_devices" ADD CONSTRAINT "fk_biometric_devices_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches" ("id");
ALTER TABLE "biotime_devices" ADD CONSTRAINT "fk_biotime_devices_company_id" FOREIGN KEY ("company_id") REFERENCES "companies" ("id");
ALTER TABLE "company_admins" ADD CONSTRAINT "fk_company_admins_company_id" FOREIGN KEY ("company_id") REFERENCES "companies" ("id");
ALTER TABLE "custom_rule" ADD CONSTRAINT "fk_custom_rule_created_by" FOREIGN KEY ("created_by") REFERENCES "employees" ("id");
ALTER TABLE "department_announcements" ADD CONSTRAINT "fk_department_announcements_sent_by" FOREIGN KEY ("sent_by") REFERENCES "employees" ("id");
ALTER TABLE "department_announcements" ADD CONSTRAINT "fk_department_announcements_department_id" FOREIGN KEY ("department_id") REFERENCES "departments" ("id");
ALTER TABLE "department_certifications" ADD CONSTRAINT "fk_department_certifications_department_id" FOREIGN KEY ("department_id") REFERENCES "departments" ("id");
ALTER TABLE "department_transfers" ADD CONSTRAINT "fk_department_transfers_from_department_id" FOREIGN KEY ("from_department_id") REFERENCES "departments" ("id");
ALTER TABLE "department_transfers" ADD CONSTRAINT "fk_department_transfers_to_department_id" FOREIGN KEY ("to_department_id") REFERENCES "departments" ("id");
ALTER TABLE "department_transfers" ADD CONSTRAINT "fk_department_transfers_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "dept_alert_recipients" ADD CONSTRAINT "fk_dept_alert_recipients_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "dept_alert_recipients" ADD CONSTRAINT "fk_dept_alert_recipients_department_id" FOREIGN KEY ("department_id") REFERENCES "departments" ("id");
ALTER TABLE "dept_required_certs" ADD CONSTRAINT "fk_dept_required_certs_department_id" FOREIGN KEY ("department_id") REFERENCES "departments" ("id");
ALTER TABLE "employee_certifications" ADD CONSTRAINT "fk_employee_certifications_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") ON DELETE CASCADE;
ALTER TABLE "employee_children" ADD CONSTRAINT "fk_employee_children_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") ON DELETE CASCADE;
ALTER TABLE "employee_delegations" ADD CONSTRAINT "fk_employee_delegations_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") ON DELETE CASCADE;
ALTER TABLE "employee_disciplinary_actions" ADD CONSTRAINT "fk_employee_disciplinary_actions_issued_by" FOREIGN KEY ("issued_by") REFERENCES "employees" ("id");
ALTER TABLE "employee_disciplinary_actions" ADD CONSTRAINT "fk_employee_disciplinary_actions_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") ON DELETE CASCADE;
ALTER TABLE "employee_documents" ADD CONSTRAINT "fk_employee_documents_uploaded_by" FOREIGN KEY ("uploaded_by") REFERENCES "employees" ("id");
ALTER TABLE "employee_documents" ADD CONSTRAINT "fk_employee_documents_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "employee_extended" ADD CONSTRAINT "fk_employee_extended_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") ON DELETE CASCADE;
ALTER TABLE "employee_extended" ADD CONSTRAINT "fk_employee_extended_grade_id" FOREIGN KEY ("grade_id") REFERENCES "employee_grades" ("id");
ALTER TABLE "employee_leave_balances" ADD CONSTRAINT "fk_employee_leave_balances_leave_type_id" FOREIGN KEY ("leave_type_id") REFERENCES "leave_types" ("id") ON DELETE CASCADE;
ALTER TABLE "employee_leave_balances" ADD CONSTRAINT "fk_employee_leave_balances_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") ON DELETE CASCADE;
ALTER TABLE "employee_leave_requests" ADD CONSTRAINT "fk_employee_leave_requests_leave_type_id" FOREIGN KEY ("leave_type_id") REFERENCES "leave_types" ("id") ON DELETE CASCADE;
ALTER TABLE "employee_leave_requests" ADD CONSTRAINT "fk_employee_leave_requests_reviewed_by" FOREIGN KEY ("reviewed_by") REFERENCES "employees" ("id");
ALTER TABLE "employee_leave_requests" ADD CONSTRAINT "fk_employee_leave_requests_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") ON DELETE CASCADE;
ALTER TABLE "employee_patterns" ADD CONSTRAINT "fk_employee_patterns_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "employee_performance" ADD CONSTRAINT "fk_employee_performance_evaluated_by" FOREIGN KEY ("evaluated_by") REFERENCES "employees" ("id");
ALTER TABLE "employee_performance" ADD CONSTRAINT "fk_employee_performance_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") ON DELETE CASCADE;
ALTER TABLE "employee_permissions" ADD CONSTRAINT "fk_employee_permissions_permission_id" FOREIGN KEY ("permission_id") REFERENCES "permissions" ("id");
ALTER TABLE "employee_permissions" ADD CONSTRAINT "fk_employee_permissions_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "employee_profiles" ADD CONSTRAINT "fk_employee_profiles_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "employee_promotions" ADD CONSTRAINT "fk_employee_promotions_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") ON DELETE CASCADE;
ALTER TABLE "employee_promotions" ADD CONSTRAINT "fk_employee_promotions_to_grade_id" FOREIGN KEY ("to_grade_id") REFERENCES "employee_grades" ("id");
ALTER TABLE "employee_promotions" ADD CONSTRAINT "fk_employee_promotions_approved_by" FOREIGN KEY ("approved_by") REFERENCES "employees" ("id");
ALTER TABLE "employee_promotions" ADD CONSTRAINT "fk_employee_promotions_from_grade_id" FOREIGN KEY ("from_grade_id") REFERENCES "employee_grades" ("id");
ALTER TABLE "employee_qualifications" ADD CONSTRAINT "fk_employee_qualifications_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") ON DELETE CASCADE;
ALTER TABLE "employee_training" ADD CONSTRAINT "fk_employee_training_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") ON DELETE CASCADE;
ALTER TABLE "employees_government" ADD CONSTRAINT "fk_employees_government_grade_id" FOREIGN KEY ("grade_id") REFERENCES "employee_grades" ("id");
ALTER TABLE "employees_government" ADD CONSTRAINT "fk_employees_government_deleted_by" FOREIGN KEY ("deleted_by") REFERENCES "employees_government" ("id");
ALTER TABLE "employees_government" ADD CONSTRAINT "fk_employees_government_department_id" FOREIGN KEY ("department_id") REFERENCES "departments" ("id");
ALTER TABLE "employees_government" ADD CONSTRAINT "fk_employees_government_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches" ("id");
ALTER TABLE "employees_government" ADD CONSTRAINT "fk_employees_government_manager_id" FOREIGN KEY ("manager_id") REFERENCES "employees_government" ("id");
ALTER TABLE "geofence_events" ADD CONSTRAINT "fk_geofence_events_zone_id" FOREIGN KEY ("zone_id") REFERENCES "geofence_zones" ("id");
ALTER TABLE "geofence_events" ADD CONSTRAINT "fk_geofence_events_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "gps_logs" ADD CONSTRAINT "fk_gps_logs_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "gps_tracking_sessions" ADD CONSTRAINT "fk_gps_tracking_sessions_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "leave_balances" ADD CONSTRAINT "fk_leave_balances_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "leave_requests" ADD CONSTRAINT "fk_leave_requests_approved_by" FOREIGN KEY ("approved_by") REFERENCES "employees" ("id");
ALTER TABLE "leave_requests" ADD CONSTRAINT "fk_leave_requests_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "location_audit_logs" ADD CONSTRAINT "fk_location_audit_logs_user_id" FOREIGN KEY ("user_id") REFERENCES "employees" ("id");
ALTER TABLE "notifications" ADD CONSTRAINT "fk_notifications_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "outing_requests" ADD CONSTRAINT "fk_outing_requests_approved_by" FOREIGN KEY ("approved_by") REFERENCES "employees" ("id");
ALTER TABLE "outing_requests" ADD CONSTRAINT "fk_outing_requests_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "payroll_audit_logs" ADD CONSTRAINT "fk_payroll_audit_logs_changed_by" FOREIGN KEY ("changed_by") REFERENCES "employees" ("id");
ALTER TABLE "payroll_audit_logs" ADD CONSTRAINT "fk_payroll_audit_logs_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "payroll_records" ADD CONSTRAINT "fk_payroll_records_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "payroll_records" ADD CONSTRAINT "fk_payroll_records_approved_by" FOREIGN KEY ("approved_by") REFERENCES "employees" ("id");
ALTER TABLE "photo_verifications" ADD CONSTRAINT "fk_photo_verifications_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "promotion_eligibility" ADD CONSTRAINT "fk_promotion_eligibility_current_grade_id" FOREIGN KEY ("current_grade_id") REFERENCES "employee_grades" ("id");
ALTER TABLE "promotion_eligibility" ADD CONSTRAINT "fk_promotion_eligibility_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") ON DELETE CASCADE;
ALTER TABLE "promotion_eligibility" ADD CONSTRAINT "fk_promotion_eligibility_target_grade_id" FOREIGN KEY ("target_grade_id") REFERENCES "employee_grades" ("id");
ALTER TABLE "qr_tokens" ADD CONSTRAINT "fk_qr_tokens_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "rbac_audit_logs" ADD CONSTRAINT "fk_rbac_audit_logs_performed_by" FOREIGN KEY ("performed_by") REFERENCES "employees" ("id");
ALTER TABLE "rbac_delegations" ADD CONSTRAINT "fk_rbac_delegations_delegate_id" FOREIGN KEY ("delegate_id") REFERENCES "employees" ("id") ON DELETE CASCADE;
ALTER TABLE "rbac_delegations" ADD CONSTRAINT "fk_rbac_delegations_delegator_id" FOREIGN KEY ("delegator_id") REFERENCES "employees" ("id") ON DELETE CASCADE;
ALTER TABLE "rbac_permission_requests" ADD CONSTRAINT "fk_rbac_permission_requests_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") ON DELETE CASCADE;
ALTER TABLE "rbac_permission_requests" ADD CONSTRAINT "fk_rbac_permission_requests_reviewed_by" FOREIGN KEY ("reviewed_by") REFERENCES "employees" ("id");
ALTER TABLE "rbac_roles" ADD CONSTRAINT "fk_rbac_roles_created_by" FOREIGN KEY ("created_by") REFERENCES "employees" ("id");
ALTER TABLE "rbac_roles" ADD CONSTRAINT "fk_rbac_roles_parent_id" FOREIGN KEY ("parent_id") REFERENCES "rbac_roles" ("id");
ALTER TABLE "refresh_tokens" ADD CONSTRAINT "fk_refresh_tokens_user_id" FOREIGN KEY ("user_id") REFERENCES "employees" ("id");
ALTER TABLE "report_corrections" ADD CONSTRAINT "fk_report_corrections_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "report_corrections" ADD CONSTRAINT "fk_report_corrections_created_by" FOREIGN KEY ("created_by") REFERENCES "employees" ("id");
ALTER TABLE "report_corrections" ADD CONSTRAINT "fk_report_corrections_reviewed_by" FOREIGN KEY ("reviewed_by") REFERENCES "employees" ("id");
ALTER TABLE "salary_advances" ADD CONSTRAINT "fk_salary_advances_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "salary_slip_archives" ADD CONSTRAINT "fk_salary_slip_archives_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "scheduled_reports" ADD CONSTRAINT "fk_scheduled_reports_created_by" FOREIGN KEY ("created_by") REFERENCES "employees" ("id");
ALTER TABLE "shift_coverage_rules" ADD CONSTRAINT "fk_shift_coverage_rules_shift_type_id" FOREIGN KEY ("shift_type_id") REFERENCES "shift_types" ("id");
ALTER TABLE "shift_schedules" ADD CONSTRAINT "fk_shift_schedules_created_by" FOREIGN KEY ("created_by") REFERENCES "employees" ("id");
ALTER TABLE "shift_schedules" ADD CONSTRAINT "fk_shift_schedules_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "shift_schedules" ADD CONSTRAINT "fk_shift_schedules_substituted_by" FOREIGN KEY ("substituted_by") REFERENCES "employees" ("id");
ALTER TABLE "shift_schedules" ADD CONSTRAINT "fk_shift_schedules_original_employee_id" FOREIGN KEY ("original_employee_id") REFERENCES "employees" ("id");
ALTER TABLE "shift_schedules" ADD CONSTRAINT "fk_shift_schedules_shift_type_id" FOREIGN KEY ("shift_type_id") REFERENCES "shift_types" ("id");
ALTER TABLE "tracking_policies" ADD CONSTRAINT "fk_tracking_policies_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "trusted_devices" ADD CONSTRAINT "fk_trusted_devices_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "trusted_locations" ADD CONSTRAINT "fk_trusted_locations_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "user_preferences" ADD CONSTRAINT "fk_user_preferences_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "approval_steps" ADD CONSTRAINT "fk_approval_steps_approver_id" FOREIGN KEY ("approver_id") REFERENCES "employees" ("id");
ALTER TABLE "approval_steps" ADD CONSTRAINT "fk_approval_steps_acted_by" FOREIGN KEY ("acted_by") REFERENCES "employees" ("id");
ALTER TABLE "approval_steps" ADD CONSTRAINT "fk_approval_steps_workflow_id" FOREIGN KEY ("workflow_id") REFERENCES "approval_workflows" ("id");
ALTER TABLE "attendance_logs" ADD CONSTRAINT "fk_attendance_logs_policy_id" FOREIGN KEY ("policy_id") REFERENCES "attendance_policies" ("id");
ALTER TABLE "attendance_logs" ADD CONSTRAINT "fk_attendance_logs_company_id" FOREIGN KEY ("company_id") REFERENCES "companies" ("id");
ALTER TABLE "attendance_logs" ADD CONSTRAINT "fk_attendance_logs_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "attendance_logs" ADD CONSTRAINT "fk_attendance_logs_device_id" FOREIGN KEY ("device_id") REFERENCES "biometric_devices" ("id");
ALTER TABLE "deduction_records" ADD CONSTRAINT "fk_deduction_records_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "deduction_records" ADD CONSTRAINT "fk_deduction_records_payroll_record_id" FOREIGN KEY ("payroll_record_id") REFERENCES "payroll_records" ("id");
ALTER TABLE "dept_allowed_devices" ADD CONSTRAINT "fk_dept_allowed_devices_device_id" FOREIGN KEY ("device_id") REFERENCES "biotime_devices" ("id");
ALTER TABLE "dept_allowed_devices" ADD CONSTRAINT "fk_dept_allowed_devices_department_id" FOREIGN KEY ("department_id") REFERENCES "departments" ("id");
ALTER TABLE "device_event_logs" ADD CONSTRAINT "fk_device_event_logs_device_id" FOREIGN KEY ("device_id") REFERENCES "biotime_devices" ("id");
ALTER TABLE "device_health_snapshots" ADD CONSTRAINT "fk_device_health_snapshots_device_id" FOREIGN KEY ("device_id") REFERENCES "biotime_devices" ("id");
ALTER TABLE "device_sync_logs" ADD CONSTRAINT "fk_device_sync_logs_device_id" FOREIGN KEY ("device_id") REFERENCES "biometric_devices" ("id");
ALTER TABLE "device_sync_logs" ADD CONSTRAINT "fk_device_sync_logs_company_id" FOREIGN KEY ("company_id") REFERENCES "companies" ("id");
ALTER TABLE "document_audit_logs" ADD CONSTRAINT "fk_document_audit_logs_performed_by" FOREIGN KEY ("performed_by") REFERENCES "employees" ("id") ON DELETE SET NULL;
ALTER TABLE "document_audit_logs" ADD CONSTRAINT "fk_document_audit_logs_document_id" FOREIGN KEY ("document_id") REFERENCES "archived_documents" ("id") ON DELETE CASCADE;
ALTER TABLE "rbac_employee_roles" ADD CONSTRAINT "fk_rbac_employee_roles_revoked_by" FOREIGN KEY ("revoked_by") REFERENCES "employees" ("id");
ALTER TABLE "rbac_employee_roles" ADD CONSTRAINT "fk_rbac_employee_roles_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") ON DELETE CASCADE;
ALTER TABLE "rbac_employee_roles" ADD CONSTRAINT "fk_rbac_employee_roles_assigned_by" FOREIGN KEY ("assigned_by") REFERENCES "employees" ("id");
ALTER TABLE "rbac_employee_roles" ADD CONSTRAINT "fk_rbac_employee_roles_role_id" FOREIGN KEY ("role_id") REFERENCES "rbac_roles" ("id") ON DELETE CASCADE;
ALTER TABLE "role_departments" ADD CONSTRAINT "fk_role_departments_department_id" FOREIGN KEY ("department_id") REFERENCES "departments" ("id") ON DELETE CASCADE;
ALTER TABLE "role_departments" ADD CONSTRAINT "fk_role_departments_role_id" FOREIGN KEY ("role_id") REFERENCES "rbac_roles" ("id") ON DELETE CASCADE;
ALTER TABLE "role_permissions" ADD CONSTRAINT "fk_role_permissions_permission_id" FOREIGN KEY ("permission_id") REFERENCES "rbac_permissions" ("id") ON DELETE CASCADE;
ALTER TABLE "role_permissions" ADD CONSTRAINT "fk_role_permissions_role_id" FOREIGN KEY ("role_id") REFERENCES "rbac_roles" ("id") ON DELETE CASCADE;
ALTER TABLE "salary_components" ADD CONSTRAINT "fk_salary_components_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "salary_components" ADD CONSTRAINT "fk_salary_components_payroll_record_id" FOREIGN KEY ("payroll_record_id") REFERENCES "payroll_records" ("id");
ALTER TABLE "shift_exceptions" ADD CONSTRAINT "fk_shift_exceptions_shift_schedule_id" FOREIGN KEY ("shift_schedule_id") REFERENCES "shift_schedules" ("id");
ALTER TABLE "shift_exceptions" ADD CONSTRAINT "fk_shift_exceptions_resolved_by" FOREIGN KEY ("resolved_by") REFERENCES "employees" ("id");
ALTER TABLE "shift_exceptions" ADD CONSTRAINT "fk_shift_exceptions_employee_id" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "shift_swap_requests" ADD CONSTRAINT "fk_shift_swap_requests_substitute_employee_id" FOREIGN KEY ("substitute_employee_id") REFERENCES "employees" ("id");
ALTER TABLE "shift_swap_requests" ADD CONSTRAINT "fk_shift_swap_requests_tgt_sched_id" FOREIGN KEY ("tgt_sched_id") REFERENCES "shift_schedules" ("id");
ALTER TABLE "shift_swap_requests" ADD CONSTRAINT "fk_shift_swap_requests_target_id" FOREIGN KEY ("target_id") REFERENCES "employees" ("id");
ALTER TABLE "shift_swap_requests" ADD CONSTRAINT "fk_shift_swap_requests_req_sched_id" FOREIGN KEY ("req_sched_id") REFERENCES "shift_schedules" ("id");
ALTER TABLE "shift_swap_requests" ADD CONSTRAINT "fk_shift_swap_requests_requester_id" FOREIGN KEY ("requester_id") REFERENCES "employees" ("id");
