CREATE TABLE IF NOT EXISTS blocked_ips (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ip_address VARCHAR(50) NOT NULL UNIQUE,
    violation_count INTEGER DEFAULT 0,
    banned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ban_expiry TIMESTAMP,
    is_permanent BOOLEAN DEFAULT 0,
    is_active BOOLEAN DEFAULT 1,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
